### ISSUE TITLE
Sabe como usar o refresh token retornado no login?

### ISSUE THREAD

**Issue by asfernandes** [opastorello/SolarZAPI#1]

**Comment by opastorello** [comment]
O `refreshToken` pode ser utilizado no cabeçalho de autorização, assim como o `token` é utilizado. 

Atualmente, o **SolarZAPI** não utiliza esse token, mas podemos modificar no método de autenticação para usar e armazenar o `refreshToken`, o que facilitaria o acesso futuro e evitaria a necessidade de novas autenticações. 

Essa abordagem poderia seguir os seguintes passos:

- **Autenticação**: Realizar a autenticação e armazenar o `refreshToken` retornado.
- **Validação**: Antes de usar o `refreshToken`, seria bom validar sua validade consultando a API.
- **Uso**: Se a validação for bem-sucedida, o sistema pode usar o `refreshToken` armazenado para autenticar novas solicitações.
- **Gerenciamento**: Podemos criar métodos específicos para gerenciar o ciclo de vida do `refreshToken`, incluindo sua criação, validação, exclusão e solicitação de um novo token quando necessário.

Com essa estrutura, poderíamos garantir uma autenticação mais robusta e uma melhor experiência, reduzindo a frequência de logins. Vale ressaltar que, atualmente, o SolarZAPI não implementa esse gerenciamento do `refreshToken`, mas poderei considerar essa funcionalidade em uma atualização futura. 

Sintam-se à vontade para contribuir com o projeto!

**Comment by asfernandes** [comment]
Obrigado pela resposta e pelo SolarZAPI.
Seria `Authorization: Bearer <refreshToken>` no endpoint https://app.solarz.com.br/cliente/authenticate?
Não consegui dessa forma.

**Comment by opastorello** [comment]
Não amigo, no endpoint `cliente/authenticate` você recebe o `refreshToken`  e  `token` após fazer a autenticação com o e-mail e senha.

Oque você tem que fazer é não usar o `token` e sim o `refreshToken` nos demais endpoints.
